title: "Digitaler Garten"
pages: ./quelle/seiten
images: ./quelle/bilder
assets: ./quelle/statisch
templates: ./templates
output: ./docs

image_sizes: 
  - 1920
  - 200
  - 80

menu:
  - title: Start
    href: ./
    img: ./images/home-200.png
  - title: Gehäkelter Topflappen
    href: ./topflappen.html
    img: ./images/topflappen-200.jpg


