# Deploy via webgen/generate.py

on:
  push:
    branches:
    - main
    paths:
    - **

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Install python
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r webgen/requirements.txt

    # Build the site
    - name: Build the site
      run: |
        python webgen/generate.py

    # Push the HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        publish_branch: main
